version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - 5000:5000
      - 9000:9000
      - 9001:9001

  postgres:
    image: postgres:14.1-bullseye
    restart: always
    shm_size: '256MB'
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  mlflow:
    build: ./mlflow
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${S3_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    entrypoint: >
      mlflow server
      -h 0.0.0.0
      --backend-store-uri postgresql://mlflow:${DB_PASSWORD}@postgres/mlflow
      --default-artifact-root s3://mlflow/

  # doc: https://docs.min.io/docs/minio-docker-quickstart-guide.html
  # doc: https://docs.min.io/docs/deploy-minio-on-docker-compose.html
  # do not use "_" in service name or setting MLFLOW_S3_ENDPOINT_URL in MLflow will fail!
  minio:
    # image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
    command:
      server /data --console-address ":9001"
    volumes:
      - minio_volume:/data

volumes:
  postgres_volume:
  minio_volume:
