version: '3'

services:

  mlflow_db:
    image: postgres:14.1-bullseye
    restart: always
    shm_size: '256MB'
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mlflow_db_volume:/var/lib/postgresql/data

  mlflow:
    build: ./mlflow
    restart: always
    ports:
      - 5000:5000
    entrypoint: >
      mlflow server
      -h 0.0.0.0
      --backend-store-uri postgresql://mlflow:${DB_PASSWORD}@mlflow_db/mlflow
      --default-artifact-root .

  # doc: https://docs.min.io/docs/minio-docker-quickstart-guide.html
  # doc: https://docs.min.io/docs/deploy-minio-on-docker-compose.html
  mlflow_s3:
    # image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
    command:
      server /date --console-address ":9001"

volumes:
  mlflow_db_volume:
